#ifndef NIBBLE_SSD1306_H
#define NIBBLE_SSD1306_H

#define SCREEN_MAX_COMMAND_SIZE 0x03

#define SCREEN_ADDRESS 0x3d

#define SCREEN_CONTROL_DATA 0x00
#define SCREEN_CONTROL_COMMAND 0x80

#define SCREEN_COMMAND_CONTRAST 0x81

#define SCREEN_COMMAND_ENTIRE_DISPLAY_ON_WITH_RAM 0xa4
#define SCREEN_COMMAND_ENTIRE_DISPLAY_ON_WITHOUT_RAM 0xa5
#define SCREEN_COMMAND_DISPLAY_NORMAL 0xa6
#define SCREEN_COMMAND_DISPLAY_INVERSE 0xa7
#define SCREEN_COMMAND_DISPLAY_OFF 0xae
#define SCREEN_COMMAND_DISPLAY_ON 0xaf

#define SCREEN_COMMAND_ADDRESSING_MODE 0x20

#endif
